[project]
name = "alt-alpha-ranker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.55.0",
    "pyyaml>=6.0.3",
]
