# Languages available on https://cyanophage.github.io/
languages:
  # - dutch
  - english
  # - estonian
  # - finnish
  # - french
  # - german
  # - hungarian
  # - italian
  # - lithuanian
  # - norweigian
  # - polish
  # - portuguese
  # - spanish
  # - swedish
