# Languages should be available on https://cyanophage.github.io/
languages:
  - english
  - dutch
  # - estonian
  # - finnish
  - french
  - german
  # - hungarian
  - italian
  # - lithuanian
  # - norweigian
  # - polish
  - portuguese
  - spanish
  # - swedish
