# Generated layouts with properly encoded URLs
# Set thumb values manually based on actual thumb key usage in layouts

layouts:
- name: qwerty
  link: https://cyanophage.github.io/playground.html?layout=qwertyuiop-asdfghjkl%3B%27zxcvbnm%2C.%2F%5C%5Eback&mode=ergo&lan=english
  thumb: false
  year: 1873
- name: dvorak
  link: https://cyanophage.github.io/playground.html?layout=%27%2C.pyfgcrl%2Faoeuidhtns-%3Bqjkxbmwvz%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 1936
- name: colemak
  link: https://cyanophage.github.io/playground.html?layout=qwfpgjluy%3B-arstdhneio%27zxcvbkm%2C.%2F%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2006
- name: colemak-dh
  link: https://cyanophage.github.io/playground.html?layout=qwfpbjluy%3B-arstgmneio%27zxcdvkh%2C.%2F%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2014
- name: graphite
  link: https://cyanophage.github.io/playground.html?layout=bldwz%27fouj%3Bnrtsgyhaei%2Cqxmcvkp.-%2F%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2023
- name: gallium
  link: https://cyanophage.github.io/playground.html?layout=bldcvzyou%2C-nrtsgphaei%2Fqxmwjkf%27%3B.%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2023
- name: canary
  link: https://cyanophage.github.io/playground.html?layout=wlypbzfou%3B-crstgmneia%27qjvdkxh%2F%2C.%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2022
- name: aptV3
  link: https://cyanophage.github.io/playground.html?layout=wgdfbqluoy-rsthkjneai%3Bxcmpvz%2C.%27%2F%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2021
- name: handsdown-neu
  link: https://cyanophage.github.io/playground.html?layout=wfmpv%2F.q%3B%27zrsntb%2Caeihjxcldg-uoyk%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2021
- name: sturdy
  link: https://cyanophage.github.io/playground.html?layout=vmlcpxfouj-strdy.naei%2Fzkqgwbh%27%3B%2C%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2021
- name: engram
  link: https://cyanophage.github.io/playground.html?layout=byou%27-ldwvzciea%2C.htsnqgxjk%2F%3Brmfp%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2021
- name: carbyne
  link: https://cyanophage.github.io/playground.html?layout=fwhgzqouypjsnrtv-aeic%27bmldk%3Bx%2C.%2F%5C%5E&mode=ergo&lan=english
  thumb: false
- name: really
  link: https://cyanophage.github.io/playground.html?layout=yuolzqchgwkiearxvsntd%27-%2F%2C.%3Bjfpmb%5C%5E&mode=ergo&lan=english
  thumb: false
- name: whorf
  link: https://cyanophage.github.io/playground.html?layout=flhdmvwou%2C%2Fsrntkgyaei-xjbzqpc%27%3B.%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2021
- name: northstar
  link: https://cyanophage.github.io/playground.html?layout=qwmbzjfou%3B-nrstgyheia%27xlcdvkp%2C.%2F%5C%5E&mode=ergo&lan=english
  thumb: false
- name: semimak
  link: https://cyanophage.github.io/playground.html?layout=flhvzqwuoy-srntkcdeai%3Bx%27bmjpg%2C.%2F%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2021
- name: mtgap
  link: https://cyanophage.github.io/playground.html?layout=ypoujkdlcw-inea%2Cmhtsr%27qz%2F.%3Bbfgvx%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2010
- name: ctgap
  link: https://cyanophage.github.io/playground.html?layout=qplcjxfou%2F-rntsgyheia%3Bzbmwvkd%27%2C.%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2022
- name: recurva
  link: https://cyanophage.github.io/playground.html?layout=frdpvqjuoy-sntcb.heai%2Fzxkgwml%3B%27%2C%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2023
- name: halmak
  link: https://cyanophage.github.io/playground.html?layout=wlrbzqgudj-shnt%2C.aeoi%27fmvc%2F%3Bpxky%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2016
- name: workman
  link: https://cyanophage.github.io/playground.html?layout=qdrwbjfup%3B-ashtgyneoi%27zxmcvkl%2C.%2F%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2010
- name: nerps
  link: https://cyanophage.github.io/playground.html?layout=xldpvzkou%3Bqnrtsgyheia-%2Fjmcwbf%27%2C.%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2022
- name: focal
  link: https://cyanophage.github.io/playground.html?layout=vlhgkqfouj-srntbycaei%2Fzxmdp%27w.%3B%2C%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2024
- name: isrt
  link: https://cyanophage.github.io/playground.html?layout=yclmkzfu%2C%27-isrtgpneao%3Bqvwdjbh%2F.x%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2021
- name: irst
  link: https://cyanophage.github.io/playground.html?layout=ylcmkzfu%2C%27-irstgbneao%3Bjxwdvph%2F.q%5C%5E&mode=ergo&lan=english
  thumb: false
- name: pine_v1
  link: https://cyanophage.github.io/playground.html?layout=ylrdwjmou%2C-csntgphaei%3Bxzqvkbf%27%2F.%5C%5E&mode=ergo&lan=english
  thumb: false
- name: pine_v4
  link: https://cyanophage.github.io/playground.html?layout=qlcmk%27fuoy-nrstwpheai%2Fjxzgvbd%3B%2C.%5C%5E&mode=ergo&lan=english
  thumb: false
- name: beakl19bis
  link: https://cyanophage.github.io/playground.html?layout=qyouzwdnck-hiea%2Cgtrsp%3Bj%27%2F.xvmlfb%5C%5E&mode=ergo&lan=english
  thumb: false
  year: 2020
- name: maltron
  link: https://cyanophage.github.io/playground.html?layout=qpycbvmuzl%3Danisfdthor%27%2C.jg%3B%2Fwk-x%5Ce&mode=ergo&lan=english
  thumb: true
  year: 1977
- name: rsthd
  link: https://cyanophage.github.io/playground.html?layout=jcyfkzl%2Cuq%3Drsthdmnaio%27%2Fvgpbxw.%3B-%5Ce&mode=ergo&lan=english
  thumb: true
  year: 2016
- name: dsthk
  link: https://cyanophage.github.io/playground.html?layout=zcwbj-mu%27q%3Ddsthkvniao%2Ffgpr%3Bxly%2C.%5Ce&mode=ergo&lan=english
  thumb: false
- name: aptmak
  link: https://cyanophage.github.io/playground.html?layout=vwfpbjluy%27%3Drsthkxnaio%3B%2Fcgdqzm%2C.-%5Ce&mode=ergo&lan=english
  thumb: false
- name: caster
  link: https://cyanophage.github.io/playground.html?layout=bwdl%3B%2Ffouj-cstrxqnaih%27vygmz%3Dp.%2Ck%5Ce&mode=ergo&lan=english
  thumb: true
  year: 2024
- name: handsdown-vibranium
  link: https://cyanophage.github.io/playground.html?layout=xwmgqz.%27jb%3Bscntk%2Caeih%3Dvpld%2F-uoyf%5Cr&mode=ergo&lan=english
  thumb: true
  year: 2023
- name: handsdown-promethium
  link: https://cyanophage.github.io/playground.html?layout=fpdlx%3Buoybzsnthk%2Caeicqvwgmj-.%27%3D%2F%5Cr&mode=ergo&lan=english
  thumb: true
  year: 2024
- name: snth
  link: https://cyanophage.github.io/playground.html?layout=xpdmq%3Dyou%2C-snthvgcaei%3Bfbkljzw%27%2F.%5Cr&mode=ergo&lan=english
  thumb: false
- name: sunlight
  link: https://cyanophage.github.io/playground.html?layout=fwhgk%2Couypjsnltv.aeic%27xbmdq%3D%3B%2F-z%5Cr&mode=ergo&lan=english
  thumb: false
- name: nordrassil
  link: https://cyanophage.github.io/playground.html?layout=qyou-jgnwk%3Dhiea.pdrslzx%2F%27%2C%3Bbcmfv%5Ct&thumb=r&mode=ergo&lan=english
  thumb: true
  year: 2024
- name: night
  link: https://cyanophage.github.io/playground.html?layout=bflkqpgou.%3Dnshtmycaei%3Bxvjdz%27w-%2F%2C%5Cr&mode=ergo&lan=english
  thumb: true
  year: 2024
- name: enthium
  link: https://cyanophage.github.io/playground.html?layout=qyuo%2Fxldwz*ciea%2Ckhtnsv%27-%3D.%3Bjmgpf%5Crb&mode=ergo&lan=english
  thumb: true
  year: 2025
- name: enthium_v11
  link: https://cyanophage.github.io/playground.html?layout=zyou%3Dqldpx%5Cciae%3Bkhtnsf%27-%2C.%2Fjmgbv*rw&mode=ergo&lan=english&thumb=r
  website: https://github.com/sunaku/enthium/tree/v11
  thumb: true
  year: 2025
- name: nordrassil_rejuvenated
  link: https://cyanophage.github.io/playground.html?layout=jyou-qgnwk%3Dhiea.mdrspvx%2F%27%2C%3Bzclfb%5Ct&thumb=r&mode=ergo&lan=english
  website: https://www.reddit.com/r/KeyboardLayouts/comments/1oqqfql/%F0%96%A3%82nordrassils_rejuvenation%EF%BE%9F_a_refinement_of_the/
  thumb: true
  year: 2025
