name: arensito
link: https://cyanophage.github.io/playground.html?layout=ql%2Cp%3D%7Cfudk-arenbgsito-zw.hjvcymx%5C
thumb: false
year: 2001
website: http://www.pvv.org/~hakonhal/main.cgi/keyboard
family: ""
