name: birdie
link: https://cyanophage.github.io/playground.html?layout=%24lpdf%27wou-%3Btsnhmgcaie%2Fvzbkqxy%2C.j%5Cr%5E&thumb=l
thumb: true
website: https://layouts.wiki/guides/start/recommendations/#birdie
year: 2025
family: ""
