name: calemog
link: https://cyanophage.github.io/playground.html?layout=xlcwkzfuy%3B-orstmbneia-qjvdgph'%2C.%5C
thumb: false
year: 0
website: https://github.com/GalileoBlues/Layout-Wiki/blob/main/AKL%20Layouts
family: ""
