name: cloudy
link: https://cyanophage.github.io/playground.html?layout=youbqzflcv%2Fiaen.mhtsr%27j%2C-p%3Bkdgwx%5C
thumb: false
year: 2024
website: https://www.reddit.com/r/KeyboardLayouts/comments/1gqp6oq/flow_a_smooth_inrolling_comfy_layout
family: ""
