name: cloudback
link: https://cyanophage.github.io/playground.html?layout=xclfk%3Bbuoj%2Frsthmynaei%27vwgdzqp-.%2C%5C
thumb: false
year: 2024
website: https://www.reddit.com/r/KeyboardLayouts/comments/1gqp6oq/flow_a_smooth_inrolling_comfy_layout
