name: cloudx
link: https://cyanophage.github.io/playground.html?layout=joubqzflcx%2Fiaenymhtsr%27%2C.-p%3Bkdgwv%5C
thumb: false
year: 2024
website: https://www.reddit.com/r/KeyboardLayouts/comments/1gqp6oq/flow_a_smooth_inrolling_comfy_layout
family: ""
