name: colemak-qi;x
link: https://cyanophage.github.io/playground.html?layout=%3Blcmkjfuyq-arstgpneio'zxwdvbh%2F.%2C%5C
thumb: false
year: 2021
website: https://github.com/DreymaR/BigBagKbdTrixPKL/tree/master/Layouts/Colemak/Cmk-Qmods#colemak-qix-by-nyfee-2021-03
