name: consoc
link: https://cyanophage.github.io/playground.html?layout=fdhwj%2Fuloy%2Cstncb-erai.kmgpz%3B%27xq%5Cv%5E&thumb=l
thumb: false
year: 2026
website: https://www.reddit.com/r/KeyboardLayouts/comments/1qgzmbl/consoc_layout_an_experiment_in_highrolls/
