name: diamond\cyan_r9
link: https://cyanophage.github.io/playground.html?layout=kyou%3B%5Cwdfv-hiaezgltsnqx.%2C%27%2Fjcpmb%3Dr&mode=ergo&lan=english&thumb=r
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond
