name: diamond\black_n9
link: https://cyanophage.github.io/playground.html?layout=pyou%3B%5Cwdgv-hiaezjrtscxk.%2C%27%2Fqlmfb%3Dn&mode=ergo&lan=english&thumb=r
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond
