name: diamond\yellow_r9
link: https://cyanophage.github.io/playground.html?layout=.you%3B%5Cgdfw-heai%27vltsnx%2Cjkz%2Fqcpmb%3Dr
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond\
