name: diamond\pink_n9
link: https://cyanophage.github.io/playground.html?layout=.uhz%3B%5Cmdgw-iaoe%27jrtscv%2Cxky%2Fqlpfb%3Dn&mode=ergo&lan=english&thumb=r
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond\
