name: diamond_pink
link: https://cyanophage.github.io/playground.html?layout=.uhfz%5Cmdcp%3Biaoe%27jrtsnv%2Ckxy%2Fqlgwb-%5Eback&mode=ansi&lan=english&thumb=l
thumb: false
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond
