name: diamond\magenta_r9
link: https://cyanophage.github.io/playground.html?layout=.uhz%3B%5Cwdfv-iaoe%27gltsnq%2Cxky%2Fjcpmb%3Dr&mode=ergo&lan=english&thumb=r
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond
