name: diamond_orange_e9
link: https://cyanophage.github.io/playground.html?layout=%27yhk%3B%5Cwdgv-ionazjrtscx%2C.pu%2Fqlmfb%3De&mode=ergo&lan=english&thumb=l
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond
