name: diamond\magenta
link: https://cyanophage.github.io/playground.html?layout=.uhjz%5Cmdcp%3Biaoe%27grtsnv%2Cxky%2Fqlfwb-%5Eback
thumb: false
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond\
