name: diamond\yellow
link: https://cyanophage.github.io/playground.html?layout=.youq%5Cmdcw%3Bheai%27grtsnx%2Cjkz%2Fvlpfb-%5Eback
thumb: false
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond\
