name: diamond\crimson_n9
link: https://cyanophage.github.io/playground.html?layout=.ugz%3B%5Cmdcp-iaoe%27jrtshv%2Cxky%2Fqlfwb%3Dn&mode=ergo&lan=english&thumb=r
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond\
