name: diamond\
link: https://cyanophage.github.io/playground.html?layout=pyouq%5Cmdcwxhiae%3Bjrtsnvk.%2C%27%2Fzlgfb-%5Eback&mode=ansi&lan=english&thumb=l
thumb: false
year: 2025
website: https://github.com/r134x7/diamond_backslash
family: diamond\
