name: diamond\red_n9
link: https://cyanophage.github.io/playground.html?layout=yfgz%3B%5Cwdcv-iaoe%27jrtshx.%2Cku%2Fqlpmb%3Dn&mode=ergo&lan=english&thumb=r
thumb: true
year: 2026
website: https://github.com/r134x7/diamond_backslash
family: diamond\
