name: diamond\black
link: https://cyanophage.github.io/playground.html?layout=pyouq%5Cmdcw%3Bhiaezvrtsnxk.%2C%27%2Fjlgfb-%5Eback&mode=ansi&lan=english&thumb=l
thumb: false
year: 2025
website: https://github.com/r134x7/diamond_backslash
family: diamond\
