name: endeu
link: https://cyanophage.github.io/playground.html?layout=q.ouyvdclf%C3%9Fhaei%2Cgtrnsj%C3%A4%C3%B6%C3%BCx%27bpmwzk%5Eback&mode=iso&thumb=l
thumb: false
year: 2026
website: https://github.com/rpnfan/EnDeu
