name: engram-2025
link: https://cyanophage.github.io/playground.html?layout=byou%27-dngvqhiae%2C.trsczkjxw%2F%3Bmlfp%5C%5E&thumb=l
year: 2025
thumb: false
website: https://github.com/binarybottle/engram
family: "engram"
