name: enthium_v14
link: https://cyanophage.github.io/playground.html?layout=qyou%3Dxldpz-ciae-khtnsw'%2C.%3B%2Fjmgfv%5Crb&thumb=r
thumb: true
year: 2026
website: https://github.com/sunaku/enthium/releases/v14
