name: enthium_v10
link: https://cyanophage.github.io/playground.html?layout=zyuo%3Bqldpx%5Cciea%2Ckhtnsf%27-%3D.%2Fjmgbv*rw&thumb=r
website: https://github.com/sunaku/enthium/tree/v10
thumb: true
year: 2025
