name: enthium_v9
link: https://cyanophage.github.io/playground.html?layout=qyuo%2Fxldwz*ciea%2Ckhtnsv%27-%3D.%3Bjmgpf%5Crb&thumb=r
website: https://github.com/sunaku/enthium/tree/v9
thumb: true
year: 2025
family: enthium
