name: enthium_v11
link: https://cyanophage.github.io/playground.html?layout=zyou%3Dqldpx%5Cciae%3Bkhtnsf%27-%2C.%2Fjmgbv*rw&thumb=r
website: https://github.com/sunaku/enthium/tree/v11
thumb: true
year: 2025
family: enthium
