name: gallium v2
link: https://cyanophage.github.io/playground.html?layout=bldcvjfou%2C-nrtsgyhaei%2Fxqmwzkp%27%3B.%5C%5E&mode=iso&thumb=l
thumb: false
year: 2024
website: https://github.com/GalileoBlues/Gallium
family: "gallium"
