name: gallium-nl
link: https://cyanophage.github.io/playground.html?layout=bldcvzfuoy%2Fnrtswpheai-xqmgj%3Bk%27%2C.%5C%5E&thumb=l
thumb: false
year: 2026
website: https://www.reddit.com/r/KeyboardLayouts/comments/1oazi45/comment/nki8r5l/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
