name: hanster-21n
link: https://cyanophage.github.io/playground.html?layout=qyouxzmlpb-hiea.dtrcs%3Bj-'%2C%2Fkgwfv%5Cn%5E&thumb=l
thumb: true
year: 2024
website: https://commons.wikimedia.org/wiki/User:VTSGsRock/the_Hanster_Keyboard_Layout
