name: hanster-21s
link: https://cyanophage.github.io/playground.html?layout=qyouxkmlpb-hiea.dtrcn%3Bj-'%2C%2Fvgwfz%5Cs%5E&thumb=l
thumb: true
year: 2024
website: https://commons.wikimedia.org/wiki/User:VTSGsRock/the_Hanster_Keyboard_Layout
family: ""
