name: hanster-21r
link: https://cyanophage.github.io/playground.html?layout=qyouxzdlfb-hiea.ptnsc%3Bj-'%2C%2Fkgmwv%5Cr%5E&thumb=l
thumb: true
year: 2024
website: https://commons.wikimedia.org/wiki/User:VTSGsRock/the_Hanster_Keyboard_Layout
family: ""
