name: hanster-23s
link: https://cyanophage.github.io/playground.html?layout=qyou-kmlpbzhiea.dtrcn%3Bjxsvf%27w%2Cg%2F%5C%5E&thumb=l
thumb: true
year: 2024
website: https://commons.wikimedia.org/wiki/User:VTSGsRock/the_Hanster_Keyboard_Layout
family: "hanster"
