name: hanster-21l
link: https://cyanophage.github.io/playground.html?layout=qyouxkgnfv-hiea.dtrcs%3Bj-'%2C%2Fwmzpb%5Cl%5E&thumb=l
thumb: true
year: 2024
website: https://commons.wikimedia.org/wiki/User:VTSGsRock/the_Hanster_Keyboard_Layout
family: ""
