name: hanster-23r
link: https://cyanophage.github.io/playground.html?layout=qyou-zdlfbwhiea.ptnsc%3Bjx%27vrkm%2Cg%2F%5C%5E&thumb=l
thumb: true
year: 2024
website: https://commons.wikimedia.org/wiki/User:VTSGsRock/the_Hanster_Keyboard_Layout
family: "hanster"
