name: Hieamtsrn
link: https://cyanophage.github.io/playground.html?layout=byou%E2%80%99kdclpqhiea%2Cmtsrnvx%E2%80%9D-.%3Fwgfjz%5C
thumb: false
year: 2014
website: https://mathematicalmulticore.wordpress.com/the-keyboard-layout-project/#comment-4976
