name: hyperroll
link: https://cyanophage.github.io/playground.html?layout=pclmvxuoyf*nsrtd.aeih-bg%27wz%2F%2Cqjk%3B%5C%3D&thumb=l
thumb: false
year: 2023
website: https://www.reddit.com/r/KeyboardLayouts/comments/122yvm4/thoughts_on_rollheavy_layouts_like_wreathy_and/
family: ""
