name: inqwerted
link: https://cyanophage.github.io/playground.html?layout=trewqpoiuy-gfdsa%3Blkjh%27bvcxz%2F.%2Cmn%5C%5E
thumb: false
year: 2024
website: https://github.com/monkeytypegame/monkeytype/pull/5880
