name: koy
link: https://cyanophage.github.io/playground.html?layout=k.o%2Cyvgclfzhaeiudtrns%C3%9Fxq%C3%BC%C3%A4%C3%B6bpwmj%27%5Eback&mode=iso&thumb=l
thumb: false
year: 2010
website: http://adnw.de/index.php?n=Main.SeitlicheNachbaranschl%c3%a4ge
