name: kyu
link: https://cyanophage.github.io/playground.html?layout=kyu%2Cqbgdlp-hiea.fstrn-zx-o%2Fwcmvj%5C
thumb: false
year: 2022
website: https://www.reddit.com/r/KeyboardLayouts/comments/vx4774/kyu_layout/
family: ""
