name: maya
link: https://cyanophage.github.io/playground.html?layout=bldgqjfou%2C*nrtsvkhaei-zxmcwpy%27%2F.%3B%5C%3D&thumb=l
thumb: false
year: null
website: https://www.reddit.com/r/KeyboardLayouts/comments/1ea825g/info_on_maya_keyboard_layout/
family: ""
