name: megamak
link: https://cyanophage.github.io/playground.html?layout=xlywkzfou%3B-crstgbneia'jvdmqph%2F%2C.%5C
thumb: false
year: 0
website: https://github.com/GalileoBlues/Layout-Wiki/blob/main/AKL%20Layouts
family: ""
