name: middlemak-nh
link: https://cyanophage.github.io/playground.html?layout=qwldgjfou%3B-nsrtpyheia-zxcvbkm%2C.%2F%5C
thumb: false
year: 2023
website: https://www.reddit.com/r/KeyboardLayouts/comments/1464vck/introducing_middlemaknh_a_variant_that_puts_all/
