name: mtgap
link: https://cyanophage.github.io/playground.html?layout=ypoujkdlcw-inea%2Cmhtsr%27qz%2F.%3Bbfgvx%5C%5E
thumb: false
year: 2010
website: https://mathematicalmulticore.wordpress.com/the-keyboard-layout-project/
