name: nerts
link: https://cyanophage.github.io/playground.html?layout=pldvxzkou%3B-nrtsgyheia%2Fqjmcwbf'%2C.%5C
thumb: false
year: 0
website: https://github.com/GalileoBlues/Layout-Wiki/blob/main/AKL%20Layouts
