name: nordrassil_rejuvenated
link: https://cyanophage.github.io/playground.html?layout=jyou-qgnwk%3Dhiea.mdrspvx%2F%27%2C%3Bzclfb%5Ct&thumb=r
website: https://www.reddit.com/r/KeyboardLayouts/comments/1oqqfql/%F0%96%A3%82nordrassils_rejuvenation%EF%BE%9F_a_refinement_of_the/
thumb: true
year: 2025
family: "nordrassil"
