name: northstar_pl
link: https://cyanophage.github.io/playground.html?layout=plwbzjfou%3B-nrstgyheia-qxcdvkm%2F.%2C%5C
thumb: false
year: 2023
website: https://www.reddit.com/r/KeyboardLayouts/comments/13e4lm4/comment/jjv85pk/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
