name: northstar_v1
link: https://cyanophage.github.io/playground.html?layout=qwmbzjfou%3B-nrstgyheia%27xlcdvkp%2C.%2F%5C%5E
thumb: false
year: 2022
website: https://www.reddit.com/r/KeyboardLayouts/comments/13e4lm4/northstar/
