name: noted
link: https://cyanophage.github.io/playground.html?layout=zyuaqpbmlfjcsieodtnrh%27vx%C3%BC%C3%A4%C3%B6wg%2C.k%C3%9F%5Eback&mode=iso&thumb=l
thumb: false
year: 2022
website: https://dariogoetz.github.io/noted-layout/index.html
