name: octa8
link: https://cyanophage.github.io/playground.html?layout=youkxgwdl%2C-iaenfbstrc%3Bq%2Fzh'vpmj.%5C
thumb: false
year: 2022
website: https://github.com/OctahedronV2/Octa8/blob/main/README.md#octa8
