name: poqtea
link: https://cyanophage.github.io/playground.html?layout=ywflmkpoq--ursnhdteai%27zxcvjbg%2C.%3B%5C%5E
thumb: false
year: 2021
website: https://keyboard-design.com/letterlayout.html?layout=poqtea.en.ansi
family: ""
