name: qgmlwy
link: https://cyanophage.github.io/playground.html?layout=qgmlwyfub%3B-dstnriaeoh%27zxcvjkp%2C.%2F%5C%5E&thumb=l
thumb: false
year: 2011
website: http://mk.bcgsc.ca/carpalx/?full_optimization
family: ""
