name: semimak-jqc
link: https://cyanophage.github.io/playground.html?layout=flhvz%27wuoy*srntkgdeai-xjbmqpc%2C.%2F%3B%5C%3D&thumb=l
thumb: false
year: 2021
website: https://github.com/semilin/semimak
