name: sertain
link: https://cyanophage.github.io/playground.html?layout=xldkvzwou%3B-srtnfgyeia%2Fqjmhbpc'%2C.%5C
thumb: false
year: 0
website: https://github.com/GalileoBlues/Layout-Wiki/blob/main/AKL%20Layouts
family: ""
