name: sturdy
link: https://cyanophage.github.io/playground.html?layout=vmlcpxfouj-strdy.naei%2Fzkqgwbh%27%3B%2C%5C%5E
thumb: false
year: 2021
website: https://o-x-e-y.github.io/layouts/sturdy/index.html
