name: trendei
link: https://cyanophage.github.io/playground.html?layout=klhw%27xfouq%3Btrndbyseia*zjmcpgv-.%2C%2F%5C%3D&thumb=l
thumb: false
year: null
website: https://keyboard-layout-battles.fly.dev/layout/46-Trendei
