name: ufo
link: https://cyanophage.github.io/playground.html?layout=umkiaet'b%2C-fqxgdsv%2Fzj-opclnhr.yw%5C
thumb: false
year: 2022
website: https://www.reddit.com/r/KeyboardLayouts/comments/uecosy/ufo_the_worst_known_layout_in_colemakdh_analyzer/
family: ""
