name: valmak
link: https://cyanophage.github.io/playground.html?layout=qwfpb%3Duoyj%5Cnlstg-eaihkzmcdv%2F%3B%2C.%27*rx&thumb=l
thumb: true
year: 2025
website: https://www.reddit.com/r/KeyboardLayouts/comments/1quwwfl/valmak_february_update/
family: ""
