name: vitrimak
link: https://cyanophage.github.io/playground.html?layout=tkvumiajbr-wx%2Ffpdgq%2Cs%3Bh.'colnzye%5C
thumb: false
year: 2021
website: https://layouts.wiki/layouts/2021/vitrimak/
family: ""
