name: wreathy
link: https://cyanophage.github.io/playground.html?layout=qgdfvjluo%2C-nsthywreai%3Bbcmpkzx%2F%27.%5C
thumb: false
year: 2023
website: https://github.com/Apsu/cmini/blob/18d79d0c8651a8169e947c5b1b449d3ff797123e/layouts/wreathy.json#L4
